version: "3"

services:
  spot-a-spot-database:
    image: "postgres:13-alpine"
    restart: unless-stopped
    ports:
      - "4321:5432"
    volumes:
      - "spot-a-spot-db-data:/var/lib/postgresql/data"
    environment:
      - "POSTGRES_USER=admin"
      - "POSTGRES_PASSWORD=admin"
      - "POSTGRES_DB=spot_a_spot_db"
volumes:
  spot-a-spot-db-data: