server:
  port: 8080
  error:
    include-message: always

spring:
  datasource:
    url: "jdbc:postgresql://${SPOT_A_SPOT_DB_ENDPOINT}:5432/spot_a_spot_db"
    username: ${SPOT_A_SPOT_DB_USERNAME}
    password: ${SPOT_A_SPOT_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  flyway:
    url: "jdbc:postgresql://${SPOT_A_SPOT_DB_ENDPOINT}:5432/spot_a_spot_db"
    user: ${SPOT_A_SPOT_DB_USERNAME}
    password: ${SPOT_A_SPOT_DB_PASSWORD}

  data:
    web:
      pageable:
        max-page-size: 10

  jpa:
    open-in-view: true
    properties:
      hibernate:
        format_sql: true
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  codec:
    max-in-memory-size: 10MB

  main:
    banner-mode: off

springdoc:
  show-actuator: true
  location: "classpath:openapi/responses.json"

cors:
  allowed-origins: "*"
  allowed-methods: "*"
  allowed-headers: "*"
  exposed-headers: "*"

management:
  endpoints:
    web:
      exposure:
        include: "health,info"

aws:
  region: eu-central-1
  s3:
    buckets:
      images: spotaspot-images

logging:
  file:
    name: "logs/${random.uuid}.log"
  level:
    root: info
    com.codeninjas.spotaspot: trace
